Troubleshooting checklists
hbs-rcs/hbsgrid-docs pull request #66
Opened 2024-02-20 19:55 UTC by kyosua

Added the following troubleshooting checklists to the main help page:

Cluster login issues
Cluster storage access issues (will update mapping instructions and link out to them)
Cluster storage permissions issues
Running jobs pending issues
Running jobs crashing issues

2024-03-05 19:33 UTC, kyosua commented on docs/help.md
> +    - When you request access, our [automated system sends the project space sponsor an email](https://hbs-rcs.github.io/hbsgrid-docs/accountmanagement/#project-space-access) to formally approve your
Technically for project spaces we *can* approve on a sponsor's behalf when truly necessary, if we otherwise have their approval in writing... not that we want to encourage faculty to work that way. Should we explicitly tell people that we can't?

2024-03-05 19:36 UTC, kyosua commented on docs/help.md
> +    - Are you using the correct path / URL? (Note here to link to mapping instructions)
More detailed instructions for the new docs is almost done and we'll link there--would rather not direct people to the old page, as a lot of it is really out of date

2024-03-05 19:43 UTC, velmela commented on docs/help.md
> +    - When you request access, our [automated system sends the project space sponsor an email](https://hbs-rcs.github.io/hbsgrid-docs/accountmanagement/#project-space-access) to formally approve your
Ah ok, what do you think about softening the language then, e.g.,:

```suggestion
    - When you request access, our [automated system sends the project space sponsor an email](https://hbs-rcs.github.io/hbsgrid-docs/accountmanagement/#project-space-access) to formally approve your access. We recommend contacting them to ensure they have received the email to approve access.
```

2024-03-25 20:45 UTC, devbioinfoguy commented on docs/help.md
> +
- Nitpicky: This should be "HBSGrid Account & Login Issues"
- Also, the bullet formatting isn't consistent: In item2, the bullet is paranthetical; in #4, the bullets are essential. Perhaps change the latter two under #4 to 4a and 4b?
- Item3 we point to the QuickStart; but it's a little confusing as 'usernames' aren't pointed out well, and hostnames are kinda there. We'll need to bring the SSH login 'sidebar' into the QuickStart.
- The idea of QuickStart has been changed / watered down. Let's discuss.

2024-03-25 22:05 UTC, devbioinfoguy requested changes
These need some touch-ups:
- consistent use of boldface text (or not)
- consistent use of bullets under the main item (explanation? more questions? more assistance)?
- consistent use of tone & tense

Ironically, the original intent with the checklists was to be short & sweet, by offering quick asks/pointers to assist the end user. These seem more wordy than I expected; and perhaps we can come up with a way to streamline them (common terms, common referrals/outlinks, etc)?

2024-03-27 18:50 UTC, velmela commented on docs/help.md
> +
Edited header. Bob and MV discussed that we will start with this format and then update the formatting.

2024-03-27 18:58 UTC, velmela commented on docs/help.md
> +    - You can also check your disk usage by running the command `df -h filepath/to/directory`.
Ah ok, I can't seem to find that quota command--could you send?

2024-03-27 22:01 UTC, velmela commented on docs/help.md
> +    - Are you doing "big data" work? Could this be done more efficiently?
MV added notes about either waiting for the jobs to finish or killing low priority jobs to prioritize others.

2024-03-28 16:20 UTC, velmela approved these changes

2024-03-28 16:21 UTC, velmela approved these changes

2024-03-28 16:21 UTC, velmela commented on docs/help.md
> +
This has been removed and we will add back at a later date.

2024-03-28 16:22 UTC, merged